version: "3.3"

services:
  accounts_db:
    image: postgres:15
    container_name: accounts_db
    restart: on-failure
    env_file:
      - .env
    volumes:
      - ./dockerfiles/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5438:5432"
