version: "3.3"

services:
  db:
    image: postgres:15
    container_name: accounts_db
    restart: always
    env_file:
      - .env
    volumes:
      - psql_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    restart: always
    env_file:
      - ./.env
    depends_on:
      - db

  nginx:
    image: nginx:1.19.2
    restart: always
    volumes:
      - ./nginx/site.conf:/etc/nginx/conf.d/site.conf:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  psql_data:
