version: "3.3"

services:
  db:
    image: postgres:15
    container_name: accounts_db
    restart: on-failure
    env_file:
      - .env
    volumes:
      - psql_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    restart: always
    env_file:
      - ./.env
    volumes:
      - static_volume:/usr/app/accounts_api/static:ro
    depends_on:
      - db

  nginx:
    image: nginx:1.19.2
    restart: always
    volumes:
      - ./site.conf:/etc/nginx/conf.d/site.conf:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/usr/app/accounts_api/static:ro
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  psql_data:
  static_volume:
